language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

script:
  - cargo build
  - cargo build --no-default-features --features 'dummy'
  - cargo test --no-default-features --features 'dummy'
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --no-default-features --features 'proc-macro')
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --features 'i128')

notifications:
  email:
    on_success: never
